_BASE_: "pg_rcnn_base.yaml"
MODEL:
  WEIGHTS: "model_final_a6e10b.pkl"
DATASETS:
  TRAIN_VIDEO_IDS: [1,2,3]
  TEST_VIDEO_IDS: [0]
INPUT:
#  MIN_SIZE_TRAIN: (160, 200)
  MIN_SIZE_TRAIN: (320, 336, 352, 368, 384, 400)
  CROP:
    ENABLED: False
    SIZE: [0.5, 0.9]
  AUG:
    EXTEND: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (20000, 40000)
  MAX_ITER: 50000
  WARMUP_FACTOR: 0.00025
  WARMUP_ITERS: 4000
DATALOADER:
  NUM_WORKERS: 4
OUTPUT_DIR: ./output/pg_rcnn/extend_aug/test_video_0/