_BASE_: "../../../../configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x.yaml"
MODEL:
  META_ARCHITECTURE: "PGRCNN"
  KEYPOINT_ON: True
  ROI_HEADS:
    NAME: PGROIHeads
    NUM_CLASSES: 1
  ROI_KEYPOINT_HEAD:
    NAME: KPGRCNNHead
    NUM_KEYPOINTS: 4
  DEVICE: cuda # cpu or cuda
#  WEIGHTS: "../../model_final_a6e10b.pkl" # "./model_final_280758.pkl"
  WEIGHTS: ./output/pg_rcnn/design_1/test_video_1/model_0029999.pth
#  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_a6e10b.pkl"
  ROI_DIGIT_HEAD:
    NAME: Kpts2DigitHead
    TRANSFORM_DIM: 9
    NUM_PROPOSAL: 5
    NUM_CONV: 5
    CONV_DIM: 64
    NUM_FC: 0
    FC_DIM: 256
    NORM: ""
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TEST: ("jerseynumbers_val",)
  DIGIT_ONLY: False
  TRAIN_VIDEO_IDS: [0,2,3]
  TEST_VIDEO_IDS: [1]
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.5, 0.9]
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01 # when IMS_PER_BATCH = 16, LR is 0.02
#  WARMUP_FACTOR: 0.001
#  WARMUP_ITERS: 1000
  STEPS: (15000, )
  MAX_ITER: 40000
DATALOADER:
  NUM_WORKERS: 4
TEST:
  KEYPOINT_OKS_SIGMAS: [0.079, 0.079, 0.107, 0.107]
OUTPUT_DIR: ./output/pg_rcnn/design_1/test_video_1/
VIS_PERIOD: 0
VERSION: 2