_BASE_: "../../../../configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x.yaml"
MODEL:
  META_ARCHITECTURE: "PGRCNN"
  KEYPOINT_ON: True
  ROI_HEADS:
    NAME: PGROIHeads
    NUM_CLASSES: 1
  ROI_KEYPOINT_HEAD:
    NAME: KPGRCNNHead
    NUM_KEYPOINTS: 4
  DEVICE: cuda # cpu or cuda
#  WEIGHTS: "../../model_final_a6e10b.pkl"
  WEIGHTS: ./output/pg_rcnn/design_1/test_video_1/model_0029999.pth
  ROI_DIGIT_HEAD:
    NAME: Kpts2DigitHead
    NUM_DIGIT_CLASSES: 10
    TRANSFORM_DIM: 9
    NUM_PROPOSAL: 3
    NUM_CONV: 5
    CONV_DIM: 64
    NUM_FC: 0
    FC_DIM: 256
    NORM: ""
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TEST: ("jerseynumbers_val",)
  DIGIT_ONLY: False
  TRAIN_VIDEO_IDS: [0,1,3]
  TEST_VIDEO_IDS: [2]
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.5, 0.9]
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01 # when IMS_PER_BATCH = 16, LR is 0.02
  STEPS: (25000, 40000)
  MAX_ITER: 50000
DATALOADER:
  NUM_WORKERS: 1
TEST:
  KEYPOINT_OKS_SIGMAS: [0.079, 0.079, 0.107, 0.107]
OUTPUT_DIR: ./output/test_run/
VIS_PERIOD: 0
VERSION: 2