_BASE_: "../../../configs/Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"
  WEIGHTS: ./output/model_0089999.pth
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 10
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]] # aspect_ratio = h / w
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TEST: ("jerseynumbers_val",)
  DIGIT_ONLY: True
  TRAIN_VIDEO_IDS: [0,1,2,3]
  TEST_VIDEO_IDS: [4]
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 16
OUTPUT_DIR: ./output
INPUT:
  MIN_SIZE_TEST: 600
TEST:
  AUG:
    ENABLED: True
    FLIP: False
    MIN_SIZES: (2600, 2800)