_BASE_: "../../../configs/Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "PGRCNN"
  KEYPOINT_ON: True
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 4
  DEVICE: cuda # cpu or cuda
  WEIGHTS: "../../../model_final_a6e10b.pkl" # "./model_final_280758.pkl"
DATASETS:
  TRAIN: ("jerseynumbers_train",)
  TEST: ("jerseynumbers_val",)
INPUT:
  CROP:
    ENABLED: False
    SIZE: [0.5, 0.9]
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.0025
  STEPS: (60000, 80000)
  MAX_ITER: 10000
DATALOADER:
  NUM_WORKERS: 4
TEST:
  KEYPOINT_OKS_SIGMAS: [0.079, 0.079, 0.107, 0.107]
VIS_PERIOD: 1
VERSION: 2